<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.5.0" />
    <ProjectReference Include="..\..\Modules\Ai\CodeCafe.Modules.Ai\CodeCafe.Modules.Ai.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\CodeCafe.Modules.Identity.Presentation\CodeCafe.Modules.Identity.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Mcp\CodeCafe.Modules.Mcp\CodeCafe.Modules.Mcp.csproj" />
    <ProjectReference Include="..\..\src\CodeCafe.Application\CodeCafe.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Notes\CodeCafe.Modules.Notes.Presentation\CodeCafe.Modules.Notes.Presentation.csproj" />
    <ProjectReference Include="..\..\src\CodeCafe.Infrastructure\CodeCafe.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CodeCafe.Shared.Presentation\CodeCafe.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>
