<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\CodeCafe.Shared.Application\CodeCafe.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\CodeCafe.Shared.Domain\CodeCafe.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\CodeCafe.Shared.Infrastructure\CodeCafe.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\CodeCafe.Modules.Notes.Application\CodeCafe.Modules.Notes.Application.csproj" />
    <ProjectReference Include="..\CodeCafe.Modules.Notes.Domain\CodeCafe.Modules.Notes.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
