<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CodeCafe.Domain.Tests" />
        <InternalsVisibleTo Include="CodeCafe.Infrastructure.Tests" />
    </ItemGroup>
</Project>
