@CodeCafe.WebApi_HostAddress = http://localhost:5042

GET {{CodeCafe.WebApi_HostAddress}}/health/live
Accept: application/json

###

GET {{CodeCafe.WebApi_HostAddress}}/health/ready
Accept: application/json

###
