<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeCafe.Domain\CodeCafe.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CodeCafe.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Markdig" Version="1.4.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
  </ItemGroup>

</Project>
