import { render } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import TipTapViewer from './TipTapViewer'

vi.mock('react-i18next', () => ({
  useTranslation: () => ({ t: (key: string) => key }),
}))

const docWithEmptyHeading = {
  type: 'doc',
  content: [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'First' }],
    },
    // An empty heading renders as <h2></h2>; it must not consume an anchor id.
    { type: 'heading', attrs: { level: 2 }, content: [] },
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Second' }],
    },
  ],
}

describe('TipTapViewer heading anchors', () => {
  it('skips empty headings and numbers only non-empty ones', () => {
    const { container } = render(<TipTapViewer content={docWithEmptyHeading} />)

    const headings = container.querySelectorAll('h2')
    expect(headings).toHaveLength(3)
    expect(headings[0].id).toBe('heading-first')
    expect(headings[1].id).toBe('')
    // Index 1, not 2: the empty heading in between must not shift the ids,
    // otherwise outline links generated by extractOutline drift off-by-one.
    expect(headings[2].id).toBe('heading-second-1')
  })
})
